remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

seo:
  title: Data Discoveries 2023
  
nav:
  - label: Home
    page: index.md
  - label: About
    page: pages/about.md
  - label: Speakers
    href: pages/speakers.md
  - search: true
    
author: Charlotte Head
