title: "Data Discoveries 2023"
logo: ""
description: "Data Discoveries Event 2023 at the University of York"

minimal_mistakes_skin: "aqua"
search: true

author:
  name     : "Data Discoveries Team"
  avatar   : ""
  bio      : "Something"
  location : "Somewhere"

kramdown:
  auto_ids: false

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

includes: ["_pages"]

atom_feed: false

# defaults:
#   # _pages
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: single
#       author_profile: false
